name: CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install allantools imufusion matplotlib numpy scipy

      - name: Install Python package
        run: python -m pip install .

      - name: Run examples
        working-directory: Examples
        run: |
          python 3d_animation.py
          python 3d_plot.py
          python allan_variance.py
          python compare_real_imu.py
          python double_integration.py
          python plot_kinematics_and_imu.py
          python sensor_models.py

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine==6.0.1
          python -m pip install build
        # use twine v6.0.1 because bug in latest version (v6.1.0)

      - name: Create distributions
        run: python -m build

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish Python package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYTHON_TOKEN }}
        run: python -m twine upload --verbose --repository pypi dist/* --skip-existing
